### ISSUE TITLE
bug: WithWaitGroup misuse

### ISSUE THREAD

**Issue by kalexmills-splunk** [splunk/pipelines#36]
`WithWaitGroup` can be easily misused like so:
```
opt := pipelines.WithWaitGroup(&wg)
out1 := pipelines.Map(ctx, in, f, opt)
out2 := pipelines.Map(ctx, out1, f, opt)
```
Since `&wg` was only incremented once on the call to `WithWaitGroup`... there is a big problem.

**Comment by kalexmills** [comment]
Closed by #37
